//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryAjaxInAsp.NETMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    using System.ComponentModel.Design;




    
    public partial class Student
    {
        public int ID { get; set; }
        public string Name { get; set; }

    
        public Nullable<int> Age { get; set; }
        public string School { get; set; }
        public Nullable<int> Class { get; set; }
        public string Division { get; set; }
        public string Status { get; set; }
    }
 
}
